#!/bin/bash

os_is_windows=false
if [ -n "${OS}" ]; then
	if [ "${OS}" == "Windows_NT" ]; then
		os_is_windows=true
	fi
fi

if [ "$os_is_windows" == true ]; then
	destination_dir=/mingw64/include
else
	destination_dir=/usr/local/include
fi

mkdir -p $destination_dir
destination=$destination_dir/cpputil
if [ -e "$destination" ]; then
	rm -rf $destination
fi

ln -s `pwd`/include/cpputil $destination
