#!/bin/bash

if [ "${OS}" == "Windows_NT" ]; then
	if [ `uname -m` == "x86_64" ]; then
		destination_dir=/mingw64/include
	else
		echo "Error: Unsupported system"
		exit 1
	fi
else
	destination_dir=/usr/local/include
fi

destination=$destination_dir/cpputil
echo "Installing to: $destination"
mkdir -p $destination_dir
if [ -e "$destination" ]; then
	rm -rf $destination
fi

ln -s `pwd`/include/cpputil $destination
